




shell:
  program: /opt/homebrew/bin/bash

env:
  TERM: xterm-256color

font:
  normal:
    # Meslo is a modified version of Apple's Menlo; this version is patched with
    # Nerd Fonts (see https://github.com/ryanoasis/nerd-fonts for details). It
    # can be installed using `brew install --cask font-meslo-lg-nerd-font`.
    # family: MesloLGS Nerd Font Mono
    family: JetBrains Mono
    style: Regular
  bold:
    style: Bold
  italic:
    style: Italic
  bold_italic:
    style: Bold Italic
  size: 14.0
  offset:
    y: -2

alt_send_esc: false

