name: dotfiles

channels:
 - conda-forge
 - defaults

dependencies:
 - r-base>=4.1
 - r-languageserver
 - r-curl
 - r-future
 - r-future.apply
 - python>=3.10
 - vim>=8.2
 - conda
 - mamba
 - compilers
 - nodejs>=17.0
 - yarn>=1.20
 - wget
 - pip
 - pip:
   - pynvim
