# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -ahoG'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi


# Aliases
alias bp='vim ~/.bash_profile'
alias sbp='source ~/.bash_profile'

alias vp='vim ~/.dotfiles/vimrc'


alias targz='tar -czvf'
alias untargz='tar -xvzf'

alias cd..='cd ..'
alias cd.='cd ..'

alias tp='vim ~/.tmux.conf'
alias ta='tmux attach -t'
alias tk='tmux kill-server'
alias tls='tmux ls'
alias stp='tmux source-file ~/.tmux.conf'
alias disks='lsblk'

alias opa='source ~/opt/octoprint/bin/activate'
alias opk='pgrep octoprint | xargs kill -9; deactivate'
alias op='opa; ~/opt/octoprint/bin/octoprint serve'


#ncores=$(lscpu | grep 'CPU(s):' | sed 's/.*\ //')

# Add to PATH
export PATH="$HOME/opt/python3/bin:$PATH"
export PATH="$HOME/opt/tmux/bin:$PATH"
export PATH="$HOME/opt/vim/bin:$PATH"
export PATH="$HOME/opt/R/bin:$PATH"
# export PATH="$HOME/opt/miniconda3/bin:$PATH"  # commented out by conda initialize
# export PATH="$HOME/opt/neovim/bin:$PATH"

#alias vim='nvim'
#export EDITOR='nvim'
# export PATH="$HOME/opt/"
stty erase '^?'


# sudo lsof -i :5000    # Shows which processes are using a particular port
# kill -9 {PID}         # kill a particular process ID

# Setting PATH for Python 3.10
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.10/bin:${PATH}"
export PATH


if [[ "$OSTYPE" == "darwin"* ]]; then

# Setting PATH for Python 3.10
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.10/bin:${PATH}"
export PATH
source ~/git-completion.bash

# Aliases
alias ll="ls -aGl"
alias gedit="open -a Gedit"
alias atom="open -a 'Atom'"
alias excel="open -a 'Microsoft Excel'"
alias usearch="/Users/Czarnewski/Documents/Tools/Usearch/usearch"
alias usearch61="/Users/Czarnewski/Documents/Tools/Usearch/usearch61"
alias myscripts="ls ~/Box\ Sync/Scripts/using"

#Exporting PATHS
export PATH="$PATH:/Users/Czarnewski/Documents/Tools/Usearch"
export PATH="$PATH:/Applications/CMake.app/Contents/bin"
export PATH="$PATH:/Users/Czarnewski/Documents/Tools/Usearch/usearch61"
export PATH="$PATH:/Users/Czarnewski/Documents/Tools/Usearch/usearch"
export PATH="$PATH:/Applications/gedit.app/Contents/MacOS/gedit"
export PATH="$PATH:/Users/Czarnewski/Documents/Tools/FastQC/fastqc"
export PATH="$PATH:/Users/Czarnewski/Box Sync/Scripts/using"
#export PS1="\[\e[;31m\][\u@\h \W]\$ \[\e[m\]"
#export PS1="\[\e[;31m\][@\h \W]\[\e[m\]\$ "

# MacPorts Installer addition on 2017-04-20_at_19:52:54: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/Czarnewski/opt/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/Czarnewski/opt/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/Czarnewski/opt/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/Czarnewski/opt/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

fi
