#!/bin/bash

###############
### ALIASES ###
###############
source ~/.dotfiles/bash/bash_aliases



# bindings to move 1 word left/right with ctrl+left/right in terminal, just some apple stuff!
bind '"^[[1;2C": "\x1bb"'
bind '"^[[1;2D": "\x1bf"'
# bindings to move 1 word left/right with ctrl+left/right in terminal, just some apple stuff!
bind '"\e[5C": forward-word'
bind '"\e[5D": backward-word'
# bindings to move 1 word left/right with ctrl+left/right in iTerm2, just some apple stuff!
bind '"\e[1;5C": forward-word'
bind '"\e[1;5D": backward-word'


##############
### PROMPT ###
##############
parse_git_branch() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}
export PS1="\u@\h \[\e[32m\]\w \[\e[91m\]\$(parse_git_branch)\[\e[00m\]$ "
export PS1="\[\e[;32m\][\u@\h \W] \e[91m\]\$(parse_git_branch)\[\e[00m\] \$ \[\e[m\]"
# export PS1="\[\e[;32m\][\u@\h \W]\$ \[\e[m\]"
# export PS1="\[\e[;32m\]\W $ \[\e[m\]"
export BASH_SILENCE_DEPRECATION_WARNING=1


####################
### EXPORT PATHS ###
####################
export PATH="$HOME/Library/Python/latest/bin:$PATH"
export PATH="$HOME/edirect:$PATH"
export PATH="$HOME/opt/nvim:$PATH"
export GIT_EDITOR=vim


### KITTY
# [ "$TERM" = "xterm-kitty" ] && alias ssh="kitty +kitten ssh"


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$("$HOME/opt/miniconda3/bin/conda" 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME/opt/miniconda3/etc/profile.d/conda.sh" ]; then
        . "$HOME/opt/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/opt/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<


if [ $(uname) == 'Darwin' ]; then 
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi



# SETS TERMINAL LANGUAGE TO ENGLISH
export LC_ALL=en_US.UTF-8
export LANG=$LANG.UTF-8



###############
### GSUTILS ###
###############

# The next line updates PATH for the Google Cloud SDK.
if [ -f "$HOME/opt/google-cloud-sdk/path.bash.inc" ]; then
  . "$HOME/opt/google-cloud-sdk/path.bash.inc" 
fi

# The next line enables shell command completion for gcloud.
if [ -f "$HOME/opt/google-cloud-sdk/completion.bash.inc" ]; then
  . "$HOME/opt/google-cloud-sdk/completion.bash.inc"
fi

# This line points the Python installation to the conda one
CLOUDSDK_PYTHON="$HOME/opt/miniconda3/bin/python"
