#!/bin/bash
###############
### ALIASES ###
###############

# FOLDERS AND FILES
alias ll='ls -ahoG --color'
alias cd..='cd ..'
alias cd.='cd ..'
alias disks='lsblk'


# DEEPLIFE
PBS='paucza@89.225.233.66'
alias pbs='ssh -Y -p 10023 $PBS'


# VSCODE
alias r="radian"
alias rp='nvim ~/.Rprofile'


# BASH
alias bp='nvim ~/.bash_profile'
alias sbp='source ~/.bash_profile'
alias ba='nvim ~/.dotfiles/bash/bash_aliases'


# ALACRITTY
alias ap='nvim ~/.config/alacritty/alacritty.yml'


# KITTY
alias icat='kitten icat'

# VIM
alias vp='nvim ~/.dotfiles/nvim/init.vim'
alias scim='sc-im'


# TMUX
alias tp='nvim ~/.tmux.conf'
alias ta='tmux attach -t'
alias tk='tmux kill-server'
alias tls='tmux ls'
alias stp='tmux source-file ~/.tmux.conf'


# CONDA
alias cel='conda env list'
alias cer='conda env remove -n'
alias cac='conda activate'
alias cde='conda deactivate'

alias mec='mamba env create -f'
alias meu='mamba env update -f'
alias mer='mamba env remove -n'


# GIT
alias ga='git add'
alias gadr='git add --dry-run'
alias gc='git commit -m'
alias gcdr='git commit --dry-run -m'
alias gps='git push'
alias gpl='git pull'
alias gst='git status'


# UPPMAX
rackham='ssh -Y paucza@rackham.uppmax.uu.se'
RACKHAM='paucza@rackham.uppmax.uu.se'


# TAR
alias targz='tar -czvf'
alias untargz='tar -xvzf'


# OCTOPRINT
alias opa='source ~/opt/octoprint/bin/activate'
alias opk='pgrep octoprint | xargs kill -9; deactivate'
alias op='opa; ~/opt/octoprint/bin/octoprint serve'



# SOFTWARE
alias chrome="open -e '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'"

