#!/bin/bash
###############
### ALIASES ###
###############

# FOLDERS AND FILES
alias ll='ls -ahoG'
alias cd..='cd ..'
alias cd.='cd ..'
alias disks='lsblk'


# BASH
alias bp='vim ~/.bash_profile'
alias sbp='source ~/.bash_profile'


# VIM
alias vp='vim ~/.dotfiles/vim/vimrc'


# TMUX
alias tp='vim ~/.tmux.conf'
alias ta='tmux attach -t'
alias tk='tmux kill-server'
alias tls='tmux ls'
alias stp='tmux source-file ~/.tmux.conf'


# GIT
alias ga='git add'
alias gc='git commit -m'
alias gps='git push'
alias gpl='git pull'


# UPPMAX
rackham='ssh -Y paucza@rackham.uppmax.uu.se'
RACKHAM='paucza@rackham.uppmax.uu.se'


# TAR
alias targz='tar -czvf'
alias untargz='tar -xvzf'


# OCTOPRINT
alias opa='source ~/opt/octoprint/bin/activate'
alias opk='pgrep octoprint | xargs kill -9; deactivate'
alias op='opa; ~/opt/octoprint/bin/octoprint serve'
