#!/bin/bash

###############
### ALIASES ###
###############
source ~/.dotfiles/bash/bash_aliases


##############
### PROMPT ###
##############
export PS1="\[\e[;32m\][\u@\h \W]\$ \[\e[m\]"
# export PS1="\[\e[;32m\]\W $ \[\e[m\]"
export BASH_SILENCE_DEPRECATION_WARNING=1


####################
### EXPORT PATHS ###
####################
export PATH="$HOME/Library/Python/latest/bin:$PATH"
export PATH="$HOME/edirect:$PATH"
export PATH="$HOME/opt/nvim:$PATH"


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$("$HOME/opt/miniconda3/bin/conda" 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME/opt/miniconda3/etc/profile.d/conda.sh" ]; then
        . "$HOME/opt/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/opt/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<


if [ $(uname) == 'Darwin' ]; then 
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi


# The next line updates PATH for the Google Cloud SDK.
if [ -f $HOME'/Downloads/google-cloud-sdk/path.bash.inc' ]; then . $HOME'/Downloads/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f $HOME'/Downloads/google-cloud-sdk/completion.bash.inc' ]; then . $HOME'/Downloads/google-cloud-sdk/completion.bash.inc'; fi


# SETS TERMINAL LANGUAGE TO ENGLISH
export LC_ALL=en_US.UTF-8
